# Generated by Django 5.0 on 2023-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_confirmed",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
    ]
