# Generated by Django 3.2.2 on 2021-05-12 14:31

import django.utils.timezone
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to="user/"),
        ),
    ]
