# Generated by Django 5.0.2 on 2024-02-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_email_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_confirmed",
            field=models.BooleanField(db_default=False),
        ),
    ]
