# Generated by Django 4.0.2 on 2022-02-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_created_on"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
