# Generated by Django 2.1.2 on 2018-10-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicsdb.Creator')),
            ],
            options={
                'verbose_name_plural': 'Credits',
                'ordering': ['creator__name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('number', models.CharField(max_length=25)),
                ('cover_date', models.DateField(blank=True, null=True, verbose_name='Cover Date')),
                ('store_date', models.DateField(blank=True, null=True, verbose_name='In Store Date')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Cover')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['series__name', 'cover_date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=350)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('volume', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_began', models.PositiveSmallIntegerField()),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=350)),
                ('desc', models.TextField(blank=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicsdb.Publisher')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['sort_name', 'year_began'],
            },
        ),
        migrations.CreateModel(
            name='SeriesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='series_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicsdb.SeriesType'),
        ),
        migrations.AddField(
            model_name='issue',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicsdb.Series'),
        ),
        migrations.AddField(
            model_name='credits',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicsdb.Issue'),
        ),
        migrations.AddField(
            model_name='credits',
            name='role',
            field=models.ManyToManyField(to='comicsdb.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='credits',
            unique_together={('creator', 'issue')},
        ),
    ]
