# Generated by Django 2.1.2 on 2018-10-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('short_desc', models.CharField(blank=True, max_length=350)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('volume', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_began', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=350)),
                ('desc', models.TextField(blank=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicsdb.Publisher')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['sort_name', 'year_began'],
            },
        ),
        migrations.CreateModel(
            name='SeriesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='series_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicsdb.SeriesType'),
        ),
    ]
