# Generated by Django 2.2.2 on 2019-06-16 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comicsdb", "0001_squashed_migrations")]

    operations = [
        migrations.AlterModelOptions(name="creator", options={"ordering": ["name"]}),
        migrations.AddField(
            model_name="creator",
            name="alias",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
