# Generated by Django 2.1.3 on 2018-11-03 21:08

from django.db import migrations

ROLES = [
    # ( Role Name, Role Order )
    ('Writer', 1),
    ('Artist', 2),
    ('Penciller', 3),
    ('Inker', 4),
    ('Colorist', 5),
    ('Letterer', 6),
    ('Cover', 7),
    ('Editor', 8),
    ('Associate Editor', 9),
]


def add_role_data(apps, schema_editor):
    Role = apps.get_model('comicsdb', 'Role')
    for role_name, role_order in ROLES:
        Role.objects.create(name=role_name, order=role_order)


def remove_role_data(app, schema_editor):
    Role = apps.get_model('comicsdb', 'Role')
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_role_data,
            remove_role_data)
    ]
