# Generated by Django 2.1.3 on 2018-11-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0001_squashed_0004_character_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='creator',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='comicsdb.Creator'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='issue',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='comicsdb.Issue'),
        ),
    ]
