# Generated by Django 2.1.2 on 2018-10-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='founded',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='short_desc',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='series',
            name='short_desc',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='series',
            name='volume',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='year_began',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='year_end',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
