# Generated by Django 4.0.4 on 2022-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0001_squashed_0007_issue_reprints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arc",
            options={},
        ),
        migrations.AlterModelOptions(
            name="character",
            options={},
        ),
        migrations.AlterModelOptions(
            name="creator",
            options={},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={},
        ),
        migrations.AddIndex(
            model_name="arc",
            index=models.Index(fields=["name"], name="arc_name_idx"),
        ),
        migrations.AddIndex(
            model_name="attribution",
            index=models.Index(fields=["content_type", "object_id"], name="ct_obj_id_idx"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["name"], name="character_name_idx"),
        ),
        migrations.AddIndex(
            model_name="creator",
            index=models.Index(fields=["name"], name="creator_name_idx"),
        ),
        migrations.AddIndex(
            model_name="credits",
            index=models.Index(fields=["issue", "creator"], name="issue_creator_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["series", "cover_date", "store_date", "number"],
                name="series_cover_store_num_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(fields=["name"], name="publisher_name_idx"),
        ),
        migrations.AddIndex(
            model_name="series",
            index=models.Index(fields=["sort_name", "year_began"], name="sort_year_began_idx"),
        ),
        migrations.AddIndex(
            model_name="series",
            index=models.Index(fields=["name"], name="series_name_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["name"], name="team_name_idx"),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(fields=["issue"], name="issue_idx"),
        ),
    ]
