# Generated by Django 3.2.9 on 2021-11-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0001_squashed_migrations"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="series",
            unique_together={("publisher", "name", "volume", "series_type")},
        ),
    ]
