# Generated by Django 2.1.2 on 2018-10-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='year_began',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
