# Generated by Django 2.1.3 on 2018-11-15 21:48

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='team/%Y/%m/%d/'),
        ),
    ]
