# Generated by Django 3.1.7 on 2021-03-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0001_new_squash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variant",
            options={"ordering": ["issue"]},
        ),
    ]
