# Generated by Django 2.1.2 on 2018-11-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='creators',
            field=models.ManyToManyField(blank=True, through='comicsdb.Credits', to='comicsdb.Creator'),
        ),
    ]
