# Generated by Django 4.0.2 on 2022-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="associated",
            field=models.ManyToManyField(blank=True, to="comicsdb.Series"),
        ),
    ]
