# Generated by Django 3.2.7 on 2021-09-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0002_add_issue_page_and_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="upc",
            field=models.CharField(blank=True, max_length=20, verbose_name="UPC Code"),
        ),
    ]
