# Generated by Django 4.0.3 on 2022-03-12 13:57

from django.db import migrations


def migrate_series_type_field(apps, schema_editor):
    """
    Migrate existing SeriesType model to Series choices.
    """

    Series = apps.get_model("comicsdb", "Series")
    SeriesType = apps.get_model("comicsdb", "SeriesType")

    def convert_series_type_to_choice(st: SeriesType) -> str:
        if st.name == "Annual Series":
            return "AN"
        elif st.name == "Cancelled Series":
            return "CA"
        elif st.name == "Graphic Novel":
            return "GN"
        elif st.name == "Hard Cover":
            return "HC"
        elif st.name == "Maxi-Series":
            return "MX"
        elif st.name == "Mini-Series":
            return "MN"
        elif st.name == "One-Shot":
            return "OS"
        elif st.name == "Ongoing Series":
            return "OG"

    all_series = Series.objects.all()
    for s in all_series:
        choice = convert_series_type_to_choice(s.series_type)
        s.type = choice

    Series.objects.bulk_update(all_series, ["type"])


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0002_series_type"),
    ]

    operations = [
        migrations.RunPython(code=migrate_series_type_field),
    ]
