# Generated by Django 2.1.3 on 2018-12-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0002_remove_redundant_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicsdb.Creator'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicsdb.Issue'),
        ),
        migrations.AlterUniqueTogether(
            name='credits',
            unique_together={('issue', 'creator')},
        ),
    ]
