# Generated by Django 3.2.11 on 2022-01-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0002_alter_series_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcharacter",
            name="edited_by",
        ),
        migrations.RemoveField(
            model_name="historicalcharacter",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcreator",
            name="edited_by",
        ),
        migrations.RemoveField(
            model_name="historicalcreator",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalissue",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalissue",
            name="edited_by",
        ),
        migrations.RemoveField(
            model_name="historicalissue",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalissue",
            name="series",
        ),
        migrations.RemoveField(
            model_name="historicalpublisher",
            name="edited_by",
        ),
        migrations.RemoveField(
            model_name="historicalpublisher",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalseries",
            name="edited_by",
        ),
        migrations.RemoveField(
            model_name="historicalseries",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalseries",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="historicalseries",
            name="series_type",
        ),
        migrations.RemoveField(
            model_name="historicalteam",
            name="edited_by",
        ),
        migrations.RemoveField(
            model_name="historicalteam",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="HistoricalArc",
        ),
        migrations.DeleteModel(
            name="HistoricalCharacter",
        ),
        migrations.DeleteModel(
            name="HistoricalCreator",
        ),
        migrations.DeleteModel(
            name="HistoricalIssue",
        ),
        migrations.DeleteModel(
            name="HistoricalPublisher",
        ),
        migrations.DeleteModel(
            name="HistoricalSeries",
        ),
        migrations.DeleteModel(
            name="HistoricalTeam",
        ),
    ]
