# Generated by Django 3.1.3 on 2020-11-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0002_split_creators_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits',
            options={'ordering': ['issue', 'creator__last_name', 'creator__first_name'], 'verbose_name_plural': 'Credits'},
        ),
        migrations.RemoveField(
            model_name='creator',
            name='name',
        ),
    ]
