# Generated by Django 2.1.3 on 2018-11-03 21:26

from django.db import migrations

SERIES_TYPES = [
    # ( Series Type Name )
    ('Ongoing Series'),
    ('Cancelled Series'),
    ('Mini-Series'),
    ('Maxi-Series'),
    ('One-Shot'),
    ('Annual Series'),
]

def add_series_type_data(apps, schema_editor):
    SeriesType = apps.get_model('comicsdb', 'SeriesType')
    for series_name in SERIES_TYPES:
        SeriesType.objects.create(name=series_name)


def remove_series_type_data(app, schema_editor):
    SeriesType = apps.get_model('comicsdb', 'SeriesType')
    SeriesType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0002_role_data'),
    ]

    operations = [
        migrations.RunPython(
            add_series_type_data,
            remove_series_type_data)
    ]
