# Generated by Django 3.2.9 on 2021-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0003_add_upc_to_variant_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arc",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="creator",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalarc",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalcharacter",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalcreator",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalteam",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
