# Generated by Django 2.1.2 on 2018-10-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0003_auto_20181029_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='creators',
        ),
    ]
