# Generated by Django 2.1.3 on 2018-11-18 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0003_auto_20181117_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
