# Generated by Django 3.2.6 on 2021-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0003_add_django_simple_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalissue",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Cover Price",
            ),
        ),
        migrations.AddField(
            model_name="historicalissue",
            name="sku",
            field=models.CharField(
                blank=True, max_length=9, verbose_name="Distributor SKU"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Cover Price",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="sku",
            field=models.CharField(
                blank=True, max_length=9, verbose_name="Distributor SKU"
            ),
        ),
    ]
