# Generated by Django 2.2.2 on 2019-06-23 18:28

import django.utils.timezone
from django.db import migrations, models


def add_created_on_data(apps, schema_editor):
    Arc = apps.get_model("comicsdb", "Arc")
    query = Arc.objects.all()
    for i in query:
        i.created_on = i.modified
        i.save()

    Character = apps.get_model("comicsdb", "Character")
    query = Character.objects.all()
    for i in query:
        i.created_on = i.modified
        i.save()

    Creator = apps.get_model("comicsdb", "Creator")
    query = Creator.objects.all()
    for i in query:
        i.created_on = i.modified
        i.save()

    Publisher = apps.get_model("comicsdb", "Publisher")
    query = Publisher.objects.all()
    for i in query:
        i.created_on = i.modified
        i.save()

    Series = apps.get_model("comicsdb", "Series")
    query = Series.objects.all()
    for i in query:
        i.created_on = i.modified
        i.save()

    Team = apps.get_model("comicsdb", "Team")
    query = Team.objects.all()
    for i in query:
        i.created_on = i.modified
        i.save()


def remove_created_on_data(apps, schema_editor):
    Arc = apps.get_model("comicsdb", "Arc")
    Arc.objects.update(created_on=django.utils.timezone.now)

    Character = apps.get_model("comicsdb", "Character")
    Character.objects.update(created_on=django.utils.timezone.now)

    Creator = apps.get_model("comicsdb", "Creator")
    Creator.objects.update(created_on=django.utils.timezone.now)

    Publisher = apps.get_model("comicsdb", "Publisher")
    Publisher.objects.update(created_on=django.utils.timezone.now)

    Series = apps.get_model("comicsdb", "Series")
    Series.objects.update(created_on=django.utils.timezone.now)

    Team = apps.get_model("comicsdb", "Team")
    Team.objects.update(created_on=django.utils.timezone.now)


class Migration(migrations.Migration):

    dependencies = [("comicsdb", "0003_issue_created_on")]

    operations = [
        migrations.AddField(
            model_name="arc",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="character",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="creator",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publisher",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="series",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.RunPython(add_created_on_data, reverse_code=remove_created_on_data),
        migrations.AlterField(
            model_name="arc",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="creator",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
