# Generated by Django 2.1.3 on 2018-12-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0003_convert_issue_name_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='name',
        ),
    ]
