# Generated by Django 2.1.3 on 2018-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0003_series_type_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='creator',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
