# Generated by Django 2.1.3 on 2018-12-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0003_modify_credits_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('series', 'number')},
        ),
    ]
