# Generated by Django 4.0.3 on 2022-03-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0003_migrate_series_type_to_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="series",
            name="series_type",
        ),
    ]
