# Generated by Django 4.0.2 on 2022-02-14 14:35

from django.db import migrations


def migrate_wikipedia_field(apps, schema_editor):
    """
    Let's move existing wikipedia field data to attribution model.
    """
    Attribution = apps.get_model("comicsdb", "Attribution")
    ContentType = apps.get_model("contenttypes", "ContentType")

    Character = apps.get_model("comicsdb", "Character")
    CharacterContentType = ContentType.objects.get_for_model(Character)
    for character in Character.objects.all():
        if character.wikipedia:
            url = f"https://en.wikipedia.org/wiki/{character.wikipedia}"
            Attribution.objects.create(
                object_id=character.id, content_type=CharacterContentType, source="W", url=url
            )

    Creator = apps.get_model("comicsdb", "Creator")
    CreatorContentType = ContentType.objects.get_for_model(Creator)
    for creator in Creator.objects.all():
        if creator.wikipedia:
            url = f"https://en.wikipedia.org/wiki/{creator.wikipedia}"
            Attribution.objects.create(
                object_id=creator.id, content_type=CreatorContentType, source="W", url=url
            )

    Publisher = apps.get_model("comicsdb", "Publisher")
    PublisherContentType = ContentType.objects.get_for_model(Publisher)
    for publisher in Publisher.objects.all():
        if publisher.wikipedia:
            url = f"https://en.wikipedia.org/wiki/{publisher.wikipedia}"
            Attribution.objects.create(
                object_id=publisher.id,
                content_type=PublisherContentType,
                source="W",
                url=url,
            )

    Team = apps.get_model("comicsdb", "Team")
    TeamContentType = ContentType.objects.get_for_model(Team)
    for team in Team.objects.all():
        if team.wikipedia:
            url = f"https://en.wikipedia.org/wiki/{team.wikipedia}"
            Attribution.objects.create(
                object_id=team.id, content_type=TeamContentType, source="W", url=url
            )


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0003_attribution"),
    ]

    operations = [
        migrations.RunPython(migrate_wikipedia_field),
    ]
