# Generated by Django 3.2.9 on 2021-11-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0004_abstract_commoninfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="series",
            field=models.ManyToManyField(
                blank=True, related_name="_comicsdb_series_series_+", to="comicsdb.Series"
            ),
        ),
    ]
