# Generated by Django 2.2.3 on 2019-07-05 13:58

from django.db import migrations, models


def add_created_on_data(apps, schema_editor):
    Series = apps.get_model("comicsdb", "Series")
    query = Series.objects.all()
    for i in query:
        if not i.volume:
            i.volume = "1"
            i.save()


def remove_created_on_data(apps, schema_editor):
    Series = apps.get_model("comicsdb", "Series")
    query = Series.objects.all()
    for i in query:
        if i.volume == "1":
            i.volume = ""
            i.save()


class Migration(migrations.Migration):

    dependencies = [("comicsdb", "0004_add_created_on_fields")]

    operations = [
        migrations.RunPython(add_created_on_data, reverse_code=remove_created_on_data),
        migrations.AlterField(
            model_name="series",
            name="volume",
            field=models.PositiveSmallIntegerField(verbose_name="Volume Number"),
        ),
        migrations.AlterUniqueTogether(
            name="series", unique_together={("publisher", "name", "volume")}
        ),
    ]
