# Generated by Django 4.0.3 on 2022-03-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0004_remove_series_series_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeriesType",
        ),
    ]
