# Generated by Django 4.0.5 on 2022-06-13 19:38

from django.db import migrations


def add_initial_genres(apps, schema_editor):
    genres = [
        "Adult",
        "Espionage",
        "Fantasy",
        "Historical",
        "Horror",
        "Humor",
        "Manga",
        "Romance",
        "Science Fiction",
        "Super-Hero",
        "War",
        "Western",
    ]
    Genre = apps.get_model("comicsdb", "Genre")
    for i in genres:
        Genre.objects.create(name=i)


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0004_series_genres"),
    ]

    operations = [
        migrations.RunPython(add_initial_genres),
    ]
