# Generated by Django 4.0.3 on 2022-03-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0004_alter_series_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeriesType",
        ),
    ]
