# Generated by Django 2.1.3 on 2018-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0004_auto_20181110_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='wikipedia',
            field=models.CharField(blank=True, max_length=255, verbose_name='Wikipedia Slug'),
        ),
    ]
