# Generated by Django 2.1.3 on 2018-12-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0004_remove_issue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='tmp_name',
            new_name='name',
        ),
    ]
