# Generated by Django 3.2.6 on 2021-08-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0004_add_price_and_sku_to_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalissue",
            name="upc",
            field=models.CharField(blank=True, max_length=14, verbose_name="UPC Code"),
        ),
        migrations.AddField(
            model_name="issue",
            name="upc",
            field=models.CharField(blank=True, max_length=14, verbose_name="UPC Code"),
        ),
    ]
