# Generated by Django 2.1.3 on 2018-11-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0005_team_wikipedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
