# Generated by Django 3.2.9 on 2021-11-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0005_series_series"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="series",
            name="series",
        ),
        migrations.AddField(
            model_name="series",
            name="associated",
            field=models.ManyToManyField(
                blank=True, related_name="_comicsdb_series_associated_+", to="comicsdb.Series"
            ),
        ),
    ]
