# Generated by Django 4.0.2 on 2022-02-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0005_remove_wiki_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attribution",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="attribution",
            name="source",
            field=models.CharField(
                choices=[("M", "Marvel"), ("W", "Wikipedia"), ("G", "Grand Comics Database")],
                default="W",
                max_length=1,
            ),
        ),
    ]
