# Generated by Django 2.1.3 on 2018-11-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0005_combine_creator_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['name', 'name']},
        ),
        migrations.RemoveField(
            model_name='creator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
