# Generated by Django 3.2.6 on 2021-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0005_add_upc_to_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalissue",
            name="upc",
            field=models.CharField(blank=True, max_length=20, verbose_name="UPC Code"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="upc",
            field=models.CharField(blank=True, max_length=20, verbose_name="UPC Code"),
        ),
    ]
