# Generated by Django 2.2.3 on 2019-07-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0005_require_series_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['series__sort_name', 'cover_date', 'store_date', 'number']},
        ),
    ]
