# Generated by Django 4.0.5 on 2022-06-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0006_issue_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, verbose_name="ISBN"),
        ),
    ]
