# Generated by Django 2.2.6 on 2019-10-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comicsdb", "0006_auto_20190717_1550")]

    operations = [
        migrations.AlterModelOptions(
            name="credits",
            options={"ordering": ["issue"], "verbose_name_plural": "Credits"},
        )
    ]
