# Generated by Django 3.2.6 on 2021-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0006_increase_upc_field_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="sku",
            field=models.CharField(blank=True, max_length=9, verbose_name="Distributor SKU"),
        ),
    ]
