# Generated by Django 2.1.3 on 2018-11-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0006_auto_20181110_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creators',
            field=models.ManyToManyField(blank=True, to='comicsdb.Creator'),
        ),
    ]
