# Generated by Django 4.0.2 on 2022-02-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0006_add_gcd_to_attribution_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="reprints",
            field=models.ManyToManyField(blank=True, to="comicsdb.Issue"),
        ),
    ]
