# Generated by Django 2.2.6 on 2019-10-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0007_fix_credits_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits',
            options={'ordering': ['issue', 'creator'], 'verbose_name_plural': 'Credits'},
        ),
    ]
