# Generated by Django 4.1.1 on 2022-10-04 14:04

from django.db import migrations, models


def add_ratings(apps, schema_editor):
    Rating = apps.get_model("comicsdb", "Rating")
    ratings = [
        Rating(name="Unknown"),
        Rating(name="Everyone", short_description="Appropriate for readers of all ages"),
        Rating(name="Teen", short_description="Appropriate for readers age 12 and older"),
        Rating(name="Teen Plus", short_description="Appropriate for readers age 15 and older"),
        Rating(name="Mature", short_description="Appropriate for readers age 17 and older"),
    ]
    Rating.objects.bulk_create(ratings)


def remove_ratings(apps, schema_editor):
    Rating = apps.get_model("comicsdb", "Rating")
    Rating.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0001_squashed_0007_issue_isbn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.RunPython(code=add_ratings, reverse_code=remove_ratings),
    ]
