# Generated by Django 2.2.6 on 2019-10-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0008_add_sort_on_creator_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits',
            options={'ordering': ['issue', 'creator__name'], 'verbose_name_plural': 'Credits'},
        ),
    ]
