# Generated by Django 4.1.1 on 2022-10-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0008_add_rating_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="rating",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="comicsdb.rating",
            ),
        ),
    ]
