# Generated by Django 4.1.4 on 2023-01-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comicsdb", "0009_add_rating_to_issue_model"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["series", "number"], name="series_number_idx"),
        ),
    ]
