# Generated by Django 4.1.9 on 2023-05-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0010_issue_series_number_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="arc",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Comic Vine ID"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="cv_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Comic Vine ID"
            ),
        ),
    ]
