# Generated by Django 4.1.9 on 2023-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0011_add_comic_vine_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="cover_hash",
            field=models.CharField(blank=True, max_length=16, verbose_name="Cover Hash"),
        ),
    ]
