# Generated by Django 5.0 on 2023-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0001_squashed_0013_comicsdb_use_db_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="collection",
            field=models.BooleanField(
                db_default=models.Value(False),
                help_text="Whether a series has a collection title. Normally this only applies to Trade Paperbacks.",
                verbose_name="Allow Collection Title",
            ),
        ),
    ]
