# Generated by Django 5.0.1 on 2024-01-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0015_universe"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="universes",
            field=models.ManyToManyField(blank=True, to="comicsdb.universe"),
        ),
        migrations.AddField(
            model_name="issue",
            name="universes",
            field=models.ManyToManyField(blank=True, to="comicsdb.universe"),
        ),
        migrations.AddField(
            model_name="team",
            name="universes",
            field=models.ManyToManyField(blank=True, to="comicsdb.universe"),
        ),
    ]
