# Generated by Django 5.0.1 on 2024-01-24 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0016_add_universe_m2m_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="universe",
            unique_together={("publisher", "name", "designation")},
        ),
    ]
