# Generated by Django 5.0.2 on 2024-02-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0017_alter_universe_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="collection",
            field=models.BooleanField(
                db_default=False,
                help_text="Whether a series has a collection title. Normally this only applies to Trade Paperbacks.",
                verbose_name="Allow Collection Title",
            ),
        ),
    ]
