# Generated by Django 5.0.3 on 2024-03-17 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0023_alter_universe_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="series", to="comicsdb.genre"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="comicsdb.publisher",
            ),
        ),
    ]
