# Generated by Django 5.0.3 on 2024-03-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsdb', '0024_alter_series_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='comicsdb.issue'),
        ),
    ]
