# Generated by Django 5.0.4 on 2024-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0025_alter_variant_issue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("success", "Success"),
                            ("link", "Link"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
            ],
        ),
    ]
