# Generated by Django 5.0.7 on 2024-07-14 16:38

from django.db import migrations, transaction
from django.db.models import Q


def merge_series_types(apps, schema_editor):
    series_type_model = apps.get_model("comicsdb", "SeriesType")
    # Old values
    cancelled = series_type_model.objects.get(name="Cancelled Series")
    ongoing = series_type_model.objects.get(name="Ongoing Series")
    # New value
    single = series_type_model.objects.create(name="Single Issue")

    series_model = apps.get_model("comicsdb", "Series")
    while series_model.objects.filter(
        Q(series_type=cancelled) | Q(series_type=ongoing)
    ).exists():
        with transaction.atomic():
            for row in series_model.objects.filter(
                Q(series_type=cancelled) | Q(series_type=ongoing)
            )[:500]:
                row.series_type = single
                row.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("comicsdb", "0027_series_status"),
    ]

    operations = [migrations.RunPython(merge_series_types)]
