# Generated by Django 5.0.8 on 2024-08-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comicsdb", "0029_imprint"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="series",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="series",
            name="imprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series",
                to="comicsdb.imprint",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="series",
            unique_together={("publisher", "imprint", "name", "volume", "series_type")},
        ),
    ]
